manifest:
  remotes:
    - name: zephyrproject
      url-base: https://github.com/andre-stefanov
  projects:
    - name: zephyr
      repo-path: zephyr
      remote: zephyrproject
      revision: stepper-velocity-float
      clone-depth: 1
      import:
        path-prefix: external
