name: 'Setup Zephyr Build Environment'
description: 'Action to setup Zephyr build environment'

runs:
  using: 'composite'
  steps:
    - name: 'Install dependencies'
      shell: bash
      run: |
        sudo apt install --no-install-recommends -y git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1 swig

    - name: 'Set up Python'
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: 'Install west'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install west

    - name: 'Initialize Zephyr workspace'
      shell: bash
      run: |
        west update
        west zephyr-export

    - name: 'Install Zephyr dependencies'
      shell: bash
      run: |
        west packages pip --install
