name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: application
        toolchains: arm-zephyr-eabi

    - name: 'Build Firmware'
      run: |
        west build -b nucleo_f446re firmware -- -DBOARD_ROOT=.