name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        board:
          - nucleo_f446re
          - native_sim
          - robin_nano
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: Setup Zephyr project
      uses: zephyrproject-rtos/action-zephyr-setup@v1
      with:
        app-path: application
        toolchains: all

    - name: 'Build Firmware'
      run: |
        west build -b ${{ matrix.board }} firmware -p -- -DBOARD_ROOT='.'